### PR TITLE
fix event hash check test

### LINKED ISSUE #45: [BUG] Test for the event hash in convert_test.go does not follow the same code path as process.go
### Current Behavior

The `TestDeriveEventsHash` in  `convert_test.go` does not follow the same code path for getting transaction results from a collection

### Expected Behavior

The `TestDeriveEventsHash ` function should fail with the current code

### Steps To Reproduce

1. go test convert_test.go
2. See it succeed

### Environment

```markdown
- OS:Mac
```

### What are you currently working on that this is blocking?

_No response_

### PR DESCRIPTION
**Pull request by koko1123**
Fixes #45

### CODE REVIEW

File: state/convert_test.go [hunk 1]
```diff
@@ -88,24 +88,30 @@ func TestDeriveEventsHash(t *testing.T) {
...
+				if !bytes.Equal(result.CollectionId, prev) {
+					col = &collectionData{}
+					cols = append(cols, col)
+				}
 			}
-			cols = append(cols, colData)
+			if idx < txnLen {
+				col.txns = append(col.txns, txns[idx])
+			}
+			col.txnResults = append(col.txnResults, result)
```
Comment (peterargue) [inline state/convert_test.go:110]: shouldn't `txns` and `txnResults ` contain the same number of elements?

File: state/convert_test.go [hunk 2]
```diff
@@ -88,24 +88,30 @@ func TestDeriveEventsHash(t *testing.T) {
 	client := spork.AccessNodes.Client()
 	for blockHeight := startBlockHeight; blockHeight < endBlockHeight; blockHeight++ {
 		block, err := client.BlockByHeight(ctx, blockHeight)
+		txns, err := client.TransactionsByBlockID(ctx, block.Id)
+		assert.NoError(t, err)
```
Comment (peterargue) [inline state/convert_test.go:92]: nit, many of these `assert.NoError` should really be `require.NoError`. `require` aborts the test immediately if it's false, which is appropriate if the condition must be true for the rest of the test to be valid.

**Review by peterargue — APPROVED** [review]

**Review by zhangchiqing — APPROVED** [review]
